#!/usr/bin/env bash
# configuring a new HAproxy as a load balancer

# Installing HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configuring haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend sammykingx.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 64820-web-01 100.26.238.50:80
        server 64820-web-02 54.236.25.179:80
' >> /etc/haproxy/haproxy.cfg

# Restarting HAproxy service
service haproxy restart
