#!/usr/bin/env bash
#What is the OSI model?
#How is the OSI model organized?

The OSI model is a model that characterizes the communication functions of a telecommunication system with a strong regard for their underlying internal structure and technology

From the lowest to the highest level
