#!/usr/bin/env bash
#A script that displays numbers from 1 to 100 and Fizzbuzz when 3 and 5stuf Fizz when 3 and Buzz when 5

count=1
while [ $count -ne 101 ]
do
    if [ $((count % 15)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((count % 3)) -eq 0 ]
    then
	echo "Fizz"
    elif [ $((count % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
	echo $count
    fi
    ((count++))
done
