#!/usr/bin/env bash
#A scripts that display hours and 59 minutes in a nested loop

hours=0
minutes=1
while [ $hours -ne 13 ]
do
    echo "Hour: $hours"
    ((hours++))
    while [ $minutes -ne 60 ]
    do
	echo $minutes
	((minutes++))
    done
    ((minutes = 1))
done
